Add config option for fail-on-impossible-test
Test may be impossible to run, for example, because the server that's being tested does not support a particular feature.

It is not unreasonable for users to assume that, upon a successful test execution result, all tests have passed. In the case of 'impossible' tests, this isn't necessarily the case: some test might not have executed at all.

Especially in scenarios where users have configured the test run to enable a specific subset of the tests (through configuration such as enabledTests and enabledSpecifications) it may be desirable to hard fail when a test was impossible to execute. This enforces that a test run was strictly successful in all tests it was configured to execute.

fixes #38

diff --git a/.github/workflows/continuous-integration.yml b/.github/workflows/continuous-integration.yml
--- a/.github/workflows/continuous-integration.yml
+++ b/.github/workflows/continuous-integration.yml
@@ -81,3 +81,35 @@ jobs:
           testId: 'provisioning-ibr'
           domain: 'example.org'
           enabledSpecifications: 'XEP-0115,XEP-0199,XEP-0352'
+
+  run-action-fail-on-impossible-test:
+
+    name: Test the 'fail-on-impossible-test' configuration option
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout local action
+        uses: actions/checkout@v4
+
+      - name: Run Openfire
+        uses: igniterealtime/launch-openfire-action@v1.2.0
+        with:
+          version: ${{env.OPENFIRE_VERSION}}
+
+      - name: Run the action that's developed in this repository
+        continue-on-error: true
+        uses: ./
+        with:
+          testId: 'fail-on-impossible-test'
+          domain: 'example.org'
+          adminAccountUsername: 'admin'
+          adminAccountPassword: 'admin'
+          enabledSpecifications: 'XEP-0215,XEP-0199'
+          failOnImpossibleTest: 'true'
+
+      - name: Assert that the action failed as expected
+        if: ${{ success() }}
+        run: |
+          echo "❌ Action execution succeeded, but failure was expected!"
+          exit 1
+        shell: bash
